import { MaterialMeta } from '../types';

export const KNOWN_MATERIALS: Record<string, MaterialMeta> = {
  pine_log: { id: 'pine_log', name: 'Tronco de Pino', category: 'wood', icon: '🪵' },
  planks: { id: 'planks', name: 'Tablas de Pino', category: 'wood', icon: '🪵' },
  strong_wood: { id: 'strong_wood', name: 'Madera Fuerte', category: 'wood', icon: '🪵' },
  yew_planks: { id: 'yew_planks', name: 'Tablas de Tejo', category: 'wood', icon: '🪵' },
  maple_log: { id: 'maple_log', name: 'Tronco de Arce', category: 'wood', icon: '🪵' },
  maple_plank: { id: 'maple_plank', name: 'Tablas de Arce', category: 'wood', icon: '🪵' },
  limestone: { id: 'limestone', name: 'Piedra Caliza', category: 'stone', icon: '🪨' },
  stone_blocks: { id: 'stone_blocks', name: 'Bloques de Piedra', category: 'stone', icon: '🧱' },
  granite: { id: 'granite', name: 'Granito', category: 'stone', icon: '🪨' },
  copper_ore: { id: 'copper_ore', name: 'Mineral de Cobre', category: 'metal', icon: '⛏️' },
  copper_ingot: { id: 'copper_ingot', name: 'Lingote de Cobre', category: 'metal', icon: '🟧' },
  bronze_ingot: { id: 'bronze_ingot', name: 'Lingote de Bronce', category: 'metal', icon: '🟫' },
  iron_ore: { id: 'iron_ore', name: 'Mineral de Hierro', category: 'metal', icon: '⛏️' },
  iron_ingot: { id: 'iron_ingot', name: 'Lingote de Hierro', category: 'metal', icon: '⬜' },
  iron_plate: { id: 'iron_plate', name: 'Placa de Hierro', category: 'metal', icon: '🛡️' },
  steel_ingot: { id: 'steel_ingot', name: 'Lingote de Acero', category: 'metal', icon: '⛓️' },
  steel_plate: { id: 'steel_plate', name: 'Placa de Acero', category: 'metal', icon: '🛡️' },
  silver: { id: 'silver', name: 'Monedas de Plata', category: 'special', icon: '🪙' },
  silver_ingot: { id: 'silver_ingot', name: 'Lingote de Plata', category: 'metal', icon: '🪙' },
  gold_ore: { id: 'gold_ore', name: 'Mineral de Oro', category: 'metal', icon: '⛏️' },
  gold_ingot: { id: 'gold_ingot', name: 'Lingote de Oro', category: 'metal', icon: '🥇' },
  nails: { id: 'nails', name: 'Clavos', category: 'metal', icon: '🔩' },
  gears: { id: 'gears', name: 'Engranajes', category: 'metal', icon: '⚙️' },
  metal_parts: { id: 'metal_parts', name: 'Piezas Metálicas', category: 'metal', icon: '🔧' },
  forged_fasteners: { id: 'forged_fasteners', name: 'Sujeción Forjada', category: 'metal', icon: '🔩' },
  chain: { id: 'chain', name: 'Cadena de Hierro', category: 'metal', icon: '⛓️' },
  pliers: { id: 'pliers', name: 'Alicates', category: 'metal', icon: '🛠️' },
  tin_ingot: { id: 'tin_ingot', name: 'Lingote de Estaño', category: 'metal', icon: '⬜' },
  tin_rod: { id: 'tin_rod', name: 'Varilla de Estaño', category: 'metal', icon: '🥢' },
  ebonite_ingot: { id: 'ebonite_ingot', name: 'Lingote de Ebonita', category: 'rare', icon: '🖤' },
  bone_fastener: { id: 'bone_fastener', name: 'Sujeción de Hueso', category: 'special', icon: '🦴' },
  leather: { id: 'leather', name: 'Cuero', category: 'cloth', icon: '🏷️' },
  leather_strips: { id: 'leather_strips', name: 'Tiras de Cuero', category: 'cloth', icon: '🏷️' },
  rope: { id: 'rope', name: 'Cuerda', category: 'cloth', icon: '🪢' },
  linen_cloth: { id: 'linen_cloth', name: 'Tela de Lino', category: 'cloth', icon: '🧵' },
  thick_fabric: { id: 'thick_fabric', name: 'Tela Gruesa', category: 'cloth', icon: '🧵' },
  piece_of_sail: { id: 'piece_of_sail', name: 'Trozo de Vela', category: 'cloth', icon: '⛵' },
  resin: { id: 'resin', name: 'Resina', category: 'rare', icon: '🍯' },
  varnish: { id: 'varnish', name: 'Barniz', category: 'rare', icon: '🧴' },
  sealing_wax: { id: 'sealing_wax', name: 'Lacre', category: 'rare', icon: '🕯️' },
  charcoal: { id: 'charcoal', name: 'Carbón vegetal', category: 'wood', icon: '⬛' },
  soul_stone: { id: 'soul_stone', name: 'Piedra de Alma', category: 'rare', icon: '💎' },
  soul_crystal: { id: 'soul_crystal', name: 'Cristal de Alma', category: 'rare', icon: '🔮' },
  dragon_scale: { id: 'dragon_scale', name: 'Escama de Dragón', category: 'rare', icon: '🐉' },
  dragon_tears: { id: 'dragon_tears', name: 'Lágrimas de Dragón', category: 'rare', icon: '💧' },
  eternal_ice: { id: 'eternal_ice', name: 'Hielo Eterno', category: 'rare', icon: '❄️' },
  ghost_flower: { id: 'ghost_flower', name: 'Flor Fantasma', category: 'rare', icon: '🌸' },
  fish_glue: { id: 'fish_glue', name: 'Pegamento de Pescado', category: 'rare', icon: '🐟' },
  alchemical_powder: { id: 'alchemical_powder', name: 'Polvo Alquímico', category: 'rare', icon: '✨' },
  sulphur: { id: 'sulphur', name: 'Azufre', category: 'rare', icon: '🧪' },
  rune_of_power: { id: 'rune_of_power', name: 'Runa de Poder', category: 'rare', icon: 'ᚱ' },
  boat_figurehead: { id: 'boat_figurehead', name: 'Mascarón de Proa', category: 'rare', icon: '🐉' },
  helm: { id: 'helm', name: 'Timón', category: 'special', icon: '☸️' },
  influencePoints: { id: 'influencePoints', name: 'Puntos de Influencia', category: 'special', icon: '🎖️' }
};

export const RARITY_COLORS = {
  common: { text: 'text-gray-300', bg: 'bg-gray-800/80', border: 'border-gray-600', badge: 'bg-gray-700 text-gray-200' },
  uncommon: { text: 'text-emerald-400', bg: 'bg-emerald-950/40', border: 'border-emerald-700/60', badge: 'bg-emerald-800/60 text-emerald-300 border border-emerald-600' },
  rare: { text: 'text-blue-400', bg: 'bg-blue-950/40', border: 'border-blue-700/60', badge: 'bg-blue-800/60 text-blue-300 border border-blue-600' },
  epic: { text: 'text-purple-400', bg: 'bg-purple-950/40', border: 'border-purple-700/60', badge: 'bg-purple-800/60 text-purple-300 border border-purple-600' },
  legendary: { text: 'text-amber-400', bg: 'bg-amber-950/40', border: 'border-amber-600/70', badge: 'bg-amber-800/60 text-amber-300 border border-amber-500' }
};
