import { MaterialMeta } from '../types';

export const KNOWN_MATERIALS: Record<string, MaterialMeta> = {
  pine_log: { id: 'pine_log', name: 'Tronco de Pino', category: 'wood', icon: '🪵', source: 'Bosques Verdes, Amarillos y Rojos' },
  planks: { id: 'planks', name: 'Tablas de Pino', category: 'wood', icon: '🪵', source: 'Banco de Carpintero (2 Troncos de Pino)' },
  strong_wood: { id: 'strong_wood', name: 'Madera Fuerte', category: 'wood', icon: '🪵', source: 'Bosques del Norte y Zonas Nevadas' },
  yew_planks: { id: 'yew_planks', name: 'Tablas de Tejo', category: 'wood', icon: '🪵', source: 'Banco de Carpintero T3 (Madera de Tejo)' },
  maple_log: { id: 'maple_log', name: 'Tronco de Arce', category: 'wood', icon: '🪵', source: 'Arboledas Rojas y Tierras Altas' },
  maple_plank: { id: 'maple_plank', name: 'Tablas de Arce', category: 'wood', icon: '🪵', source: 'Banco de Carpintero T4' },
  limestone: { id: 'limestone', name: 'Piedra Caliza', category: 'stone', icon: '🪨', source: 'Riscos Verdes, Amarillos y Rocas de Llanura' },
  stone_blocks: { id: 'stone_blocks', name: 'Bloques de Piedra', category: 'stone', icon: '🧱', source: 'Mesa de Cantero (2 Piedras Calizas)' },
  granite: { id: 'granite', name: 'Granito', category: 'stone', icon: '🪨', source: 'Riscos Rojos y Zonas Nevadas' },
  copper_ore: { id: 'copper_ore', name: 'Mineral de Cobre', category: 'metal', icon: '⛏️', source: 'Vetas de Cobre en Riscos Amarillos' },
  copper_ingot: { id: 'copper_ingot', name: 'Lingote de Cobre', category: 'metal', icon: '🟧', source: 'Horno de Fundición (2 Minerales de Cobre)' },
  bronze_ingot: { id: 'bronze_ingot', name: 'Lingote de Bronce', category: 'metal', icon: '🟫', source: 'Horno de Fundición (Cobre + Estaño)' },
  iron_ore: { id: 'iron_ore', name: 'Mineral de Hierro', category: 'metal', icon: '⛏️', source: 'Riscos Rojos y Minas Subterráneas' },
  iron_ingot: { id: 'iron_ingot', name: 'Lingote de Hierro', category: 'metal', icon: '⬜', source: 'Horno de Fundición (2 Minerales de Hierro)' },
  iron_plate: { id: 'iron_plate', name: 'Placa de Hierro', category: 'metal', icon: '🛡️', source: 'Yunque de Armero (2 Lingotes de Hierro)' },
  steel_ingot: { id: 'steel_ingot', name: 'Lingote de Acero', category: 'metal', icon: '⛓️', source: 'Horno Avanzado (Hierro + Carbón + Estaño)' },
  steel_plate: { id: 'steel_plate', name: 'Placa de Acero', category: 'metal', icon: '🛡️', source: 'Yunque de Acero (2 Lingotes de Acero)' },
  silver: { id: 'silver', name: 'Monedas de Plata', category: 'special', icon: '🪙', source: 'Cofres de Mazmorras, Saqueo y Torneos' },
  silver_ingot: { id: 'silver_ingot', name: 'Lingote de Plata', category: 'metal', icon: '🪙', source: 'Fundición de Monedas y Alijo de Asedios' },
  gold_ore: { id: 'gold_ore', name: 'Mineral de Oro', category: 'metal', icon: '⛏️', source: 'Tierras del Norte y Minas Profundas' },
  gold_ingot: { id: 'gold_ingot', name: 'Lingote de Oro', category: 'metal', icon: '🥇', source: 'Horno Avanzado (Minerales de Oro)' },
  nails: { id: 'nails', name: 'Clavos', category: 'metal', icon: '🔩', source: 'Yunque de Armero (1 Lingote de Hierro)' },
  gears: { id: 'gears', name: 'Engranajes', category: 'metal', icon: '⚙️', source: 'Cofres de Mazmorras, Sótanos y Alijo de Asedio' },
  metal_parts: { id: 'metal_parts', name: 'Piezas Metálicas', category: 'metal', icon: '🔧', source: 'Desguace en Banco de Trabajo y Cofres' },
  forged_fasteners: { id: 'forged_fasteners', name: 'Sujeción Forjada', category: 'metal', icon: '🔩', source: 'Yunque (Lingote de Hierro + Clavos)' },
  chain: { id: 'chain', name: 'Cadena de Hierro', category: 'metal', icon: '⛓️', source: 'Yunque de Herrero (Hierro + Sujeciones)' },
  pliers: { id: 'pliers', name: 'Alicates', category: 'metal', icon: '🛠️', source: 'Sanctum de Odín, Sótanos y Tumbas Antiguas' },
  tin_ingot: { id: 'tin_ingot', name: 'Lingote de Estaño', category: 'metal', icon: '⬜', source: 'Riscos del Norte y Cofres de Tumbas' },
  tin_rod: { id: 'tin_rod', name: 'Varilla de Estaño', category: 'metal', icon: '🥢', source: 'Mesa de Herrería Avanzada' },
  ebonite_ingot: { id: 'ebonite_ingot', name: 'Lingote de Ebonita', category: 'rare', icon: '🖤', source: 'Santuarios Legendarios y Eventos PvP' },
  bone_fastener: { id: 'bone_fastener', name: 'Sujeción de Hueso', category: 'special', icon: '🦴', source: 'Tumbas, Criptas de Esqueletos y Asedios' },
  leather: { id: 'leather', name: 'Cuero', category: 'cloth', icon: '🏷️', source: 'Secador de Pieles (Pieles de Lobo/Oso)' },
  leather_strips: { id: 'leather_strips', name: 'Tiras de Cuero', category: 'cloth', icon: '🏷️', source: 'Mesa de Curtido (Cortando Cuero)' },
  rope: { id: 'rope', name: 'Cuerda', category: 'cloth', icon: '🪢', source: 'Telar (Hierba de Lino silvestre)' },
  linen_cloth: { id: 'linen_cloth', name: 'Tela de Lino', category: 'cloth', icon: '🧵', source: 'Telar (Hierbas de Lino)' },
  thick_fabric: { id: 'thick_fabric', name: 'Tela Gruesa', category: 'cloth', icon: '🧵', source: 'Telar Avanzado (Lino + Algodón del Norte)' },
  piece_of_sail: { id: 'piece_of_sail', name: 'Trozo de Vela', category: 'cloth', icon: '⛵', source: 'Naufragios, Orilla y Criptas Costeras' },
  resin: { id: 'resin', name: 'Resina', category: 'rare', icon: '🍯', source: 'Talando Árboles en Bosques Rojos y Amarillos' },
  varnish: { id: 'varnish', name: 'Barniz', category: 'rare', icon: '🧴', source: 'Mesa de Alquimia (Resina + Alcohol)' },
  sealing_wax: { id: 'sealing_wax', name: 'Lacre', category: 'rare', icon: '🕯️', source: 'Cofres de Sanctum y Tumbas Antiguas' },
  charcoal: { id: 'charcoal', name: 'Carbón vegetal', category: 'wood', icon: '⬛', source: 'Carbonera (Quemando Troncos de Pino)' },
  soul_stone: { id: 'soul_stone', name: 'Piedra de Alma', category: 'rare', icon: '💎', source: 'Derrotando Jefes de Tumbas y Mazmorras' },
  soul_crystal: { id: 'soul_crystal', name: 'Cristal de Alma', category: 'rare', icon: '🔮', source: 'Cofres de Salón de Odín y Cementerio' },
  dragon_scale: { id: 'dragon_scale', name: 'Escama de Dragón', category: 'rare', icon: '🐉', source: 'Santuarios Legendarios del Dragón' },
  dragon_tears: { id: 'dragon_tears', name: 'Lágrimas de Dragón', category: 'rare', icon: '💧', source: 'Altar de Ofrendas y Eventos Especiales' },
  eternal_ice: { id: 'eternal_ice', name: 'Hielo Eterno', category: 'rare', icon: '❄️', source: 'Tierras Glaciares del Norte Extremo' },
  ghost_flower: { id: 'ghost_flower', name: 'Flor Fantasma', category: 'rare', icon: '🌸', source: 'Recolectada de Noche en Cementerios y Criptas' },
  fish_glue: { id: 'fish_glue', name: 'Pegamento de Pescado', category: 'rare', icon: '🐟', source: 'Caldero de Cocina (Cocinando Pescados de Lago)' },
  alchemical_powder: { id: 'alchemical_powder', name: 'Polvo Alquímico', category: 'rare', icon: '✨', source: 'Mesa de Alquimia y Jefes de Odín' },
  sulphur: { id: 'sulphur', name: 'Azufre', category: 'rare', icon: '🧪', source: 'Zonas Rocosas Volcánicas y Minas Rojas' },
  rune_of_power: { id: 'rune_of_power', name: 'Runa de Poder', category: 'rare', icon: 'ᚱ', source: 'Cofres de Nivel Heroico de Odín' },
  boat_figurehead: { id: 'boat_figurehead', name: 'Mascarón de Proa', category: 'rare', icon: '🐉', source: 'Tesoro de la Costa y Muelle de Drakkars' },
  helm: { id: 'helm', name: 'Timón', category: 'special', icon: '☸️', source: 'Naufragios y Evento del Barco Hundido' },
  influencePoints: { id: 'influencePoints', name: 'Puntos de Influencia', category: 'special', icon: '🎖️', source: 'Completando Tareas Diarias, Ofrendas y Odín' },
  mastery_points: { id: 'mastery_points', name: 'Puntos de Maestría', category: 'special', icon: '🔥', source: 'Sacrificando Armas y Armaduras en el Altar de Odín' },
  gunpowder: { id: 'gunpowder', name: 'Pólvora', category: 'rare', icon: '🧨', source: 'Mesa de Alquimia (Azufre + Carbón vegetal)' },
  bomb: { id: 'bomb', name: 'Bomba de Pólvora', category: 'rare', icon: '💣', source: 'Banco de Trabajo (5 Pólvora, 5 Placas, 5 Cuerdas, 1 Sujeción)' },
  lockpick: { id: 'lockpick', name: 'Ganzúa Simple', category: 'metal', icon: '🗝️', source: 'Mesa de Armero (Piezas de metal + Clavos)' },
  master_lockpick: { id: 'master_lockpick', name: 'Ganzúa Maestra', category: 'rare', icon: '🔑', source: 'Cofres de Sanctum de Odín y Alijos Secretos' }
};

export const RARITY_COLORS = {
  common: { text: 'text-gray-300', bg: 'bg-gray-800/80', border: 'border-gray-600', badge: 'bg-gray-700 text-gray-200' },
  uncommon: { text: 'text-emerald-400', bg: 'bg-emerald-950/40', border: 'border-emerald-700/60', badge: 'bg-emerald-800/60 text-emerald-300 border border-emerald-600' },
  rare: { text: 'text-blue-400', bg: 'bg-blue-950/40', border: 'border-blue-700/60', badge: 'bg-blue-800/60 text-blue-300 border border-blue-600' },
  epic: { text: 'text-purple-400', bg: 'bg-purple-950/40', border: 'border-purple-700/60', badge: 'bg-purple-800/60 text-purple-300 border border-purple-600' },
  legendary: { text: 'text-amber-400', bg: 'bg-amber-950/40', border: 'border-amber-600/70', badge: 'bg-amber-800/60 text-amber-300 border border-amber-500' }
};
