import React, { useState } from 'react';
import { useInventoryStore } from '../../stores/useInventoryStore';
import {
  calculateDonationPoints,
  getRecommendedDonationPlans
} from '../../lib/calculations';
import itemsDataRaw from '../../data/items.json';
import classesDataRaw from '../../data/classes.json';
import { ItemDonation, ClassData, ClassBase, Rarity } from '../../types';
import { KNOWN_MATERIALS, RARITY_COLORS } from '../../constants/materials';
import {
  Flame,
  Search,
  Plus,
  Trash2,
  AlertTriangle,
  Award,
  Crown,
  Zap,
  Info
} from 'lucide-react';

const itemsData = itemsDataRaw.items as ItemDonation[];
const classesData = classesDataRaw.classes as ClassData[];

export const AltarCalculator: React.FC = () => {
  const {
    altarMode,
    altarTargetPoints,
    altarSelectedClass,
    altarTargetClassLevel,
    altarBatch,
    setAltarMode,
    setAltarTargetPoints,
    setAltarClassGoal,
    addBatchItem,
    updateBatchItem,
    removeBatchItem,
    clearBatch
  } = useInventoryStore();

  // Local state for durability in inverse mode (default 100%)
  const [inverseDurability, setInverseDurability] = useState<number>(100);

  // Catalog search & filter state
  const [catalogSearch, setCatalogSearch] = useState('');
  const [catalogRarityFilter, setCatalogRarityFilter] = useState<string>('all');
  const [catalogTypeFilter, setCatalogTypeFilter] = useState<string>('all');

  // Selected class data
  const currentClassData = classesData.find(c => c.id === altarSelectedClass) || classesData[0];

  // Recommended plans for inverse calculator
  const recommendedPlans = getRecommendedDonationPlans(altarTargetPoints, itemsData, inverseDurability);

  // Total points generated by batch in direct mode
  const totalBatchPoints = altarBatch.reduce((sum, entry) => {
    const item = itemsData.find(i => i.id === entry.itemId);
    if (!item) return sum;
    return sum + calculateDonationPoints(item.masteryPoints, entry.durability, entry.quantity);
  }, 0);

  // Quick preset points setter from class goals
  const handleSelectClassGoal = (classId: ClassBase, level: number) => {
    const cls = classesData.find(c => c.id === classId);
    if (!cls) return;
    const lvlObj = cls.levels.find(l => l.level === level);
    if (!lvlObj) return;
    setAltarClassGoal(classId, level);
    setAltarTargetPoints(lvlObj.requiredPoints);
  };

  // Filtered items for catalog
  const filteredCatalogItems = itemsData.filter(item => {
    const matchesSearch = item.name.toLowerCase().includes(catalogSearch.toLowerCase()) ||
      item.nameEn.toLowerCase().includes(catalogSearch.toLowerCase());
    const matchesRarity = catalogRarityFilter === 'all' || item.rarity === catalogRarityFilter;
    const matchesType = catalogTypeFilter === 'all' || item.type === catalogTypeFilter;
    return matchesSearch && matchesRarity && matchesType;
  });

  return (
    <div className="space-y-6 pb-12">
      {/* Header Banner */}
      <div className="rounded-2xl bg-gradient-to-r from-nordic-surface via-nordic-card to-nordic-surface border border-nordic-border p-6 shadow-xl relative overflow-hidden">
        <div className="absolute right-0 top-0 w-96 h-96 bg-amber-500/5 rounded-full blur-3xl pointer-events-none" />
        <div className="relative z-10 flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="text-2xl">⚔️</span>
              <h1 className="text-2xl sm:text-3xl font-runic font-bold text-nordic-text">
                Altar de Odín & Maestría
              </h1>
            </div>
            <p className="text-sm text-nordic-muted max-w-2xl">
              Optimiza el sacrificio de armas y armaduras para ganar Puntos de Maestría, subir niveles de clase y desbloquear talentos nórdicos.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <span className="px-3 py-1.5 rounded-xl bg-nordic-surface border border-nordic-gold/40 text-nordic-gold text-xs font-mono font-medium flex items-center gap-1.5">
              <Flame className="w-3.5 h-3.5 text-amber-500 animate-pulse" />
              Altar Activo
            </span>
          </div>
        </div>
      </div>

      {/* Selector de Modo: Inverso vs Directo vs Catálogo */}
      <div className="grid grid-cols-3 gap-2 bg-nordic-surface p-1.5 rounded-2xl border border-nordic-border">
        <button
          onClick={() => setAltarMode('inverse')}
          className={`py-3 px-3 rounded-xl text-xs sm:text-sm font-medium transition-all flex flex-col sm:flex-row items-center justify-center gap-1.5 ${
            altarMode === 'inverse'
              ? 'bg-nordic-gold text-black font-bold shadow-md'
              : 'text-nordic-muted hover:text-nordic-text hover:bg-nordic-card'
          }`}
        >
          <span>🎯</span>
          <span>Optimizador de Donación</span>
        </button>

        <button
          onClick={() => setAltarMode('direct')}
          className={`py-3 px-3 rounded-xl text-xs sm:text-sm font-medium transition-all flex flex-col sm:flex-row items-center justify-center gap-1.5 ${
            altarMode === 'direct'
              ? 'bg-nordic-gold text-black font-bold shadow-md'
              : 'text-nordic-muted hover:text-nordic-text hover:bg-nordic-card'
          }`}
        >
          <span>⚖️</span>
          <span>Calculador de Lote ({altarBatch.length})</span>
        </button>

        <button
          onClick={() => setAltarMode('catalog')}
          className={`py-3 px-3 rounded-xl text-xs sm:text-sm font-medium transition-all flex flex-col sm:flex-row items-center justify-center gap-1.5 ${
            altarMode === 'catalog'
              ? 'bg-nordic-gold text-black font-bold shadow-md'
              : 'text-nordic-muted hover:text-nordic-text hover:bg-nordic-card'
          }`}
        >
          <span>📖</span>
          <span>Catálogo de Ítems</span>
        </button>
      </div>

      {/* ========================================================= */}
      {/* MODO 1: OPTIMIZADOR / CALCULADOR INVERSO                   */}
      {/* ========================================================= */}
      {altarMode === 'inverse' && (
        <div className="space-y-6">
          {/* Panel de Metas Rápidas por Clase */}
          <div className="bg-nordic-surface rounded-2xl border border-nordic-border p-5 shadow-lg space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div>
                <h3 className="text-sm font-semibold text-nordic-text flex items-center gap-2">
                  <Award className="w-4 h-4 text-nordic-gold" />
                  Seleccionar Meta por Clase
                </h3>
                <p className="text-xs text-nordic-muted">
                  Elige qué clase quieres desbloquear o subir para ajustar los puntos automáticamente.
                </p>
              </div>

              {/* Botones de Clase Base */}
              <div className="flex items-center gap-1.5">
                {classesData.map(cls => (
                  <button
                    key={cls.id}
                    onClick={() => handleSelectClassGoal(cls.id, altarTargetClassLevel)}
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                      altarSelectedClass === cls.id
                        ? 'bg-nordic-gold/20 text-nordic-gold border border-nordic-gold/60 font-bold'
                        : 'bg-nordic-card text-nordic-muted hover:text-nordic-text border border-nordic-border'
                    }`}
                  >
                    {cls.name.split(' ')[0]}
                  </button>
                ))}
              </div>
            </div>

            {/* Selectores de Nivel de Clase */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2.5">
              {currentClassData.levels
                .filter(lvl => lvl.level > 1)
                .map(lvl => {
                  const picosNeeded = Math.ceil(lvl.requiredPoints / 18);
                  const espadasNeeded = Math.ceil(lvl.requiredPoints / 24);
                  const isSelected = altarTargetClassLevel === lvl.level;

                  return (
                    <button
                      key={lvl.level}
                      onClick={() => handleSelectClassGoal(altarSelectedClass, lvl.level)}
                      className={`p-3 rounded-xl border text-left transition-all ${
                        isSelected
                          ? 'bg-nordic-card border-nordic-gold text-nordic-text shadow-sm'
                          : 'bg-nordic-card/40 border-nordic-border text-nordic-muted hover:border-nordic-border/80'
                      }`}
                    >
                      <div className="flex items-center justify-between mb-1">
                        <span className="font-bold text-xs text-nordic-text">Nivel {lvl.level}</span>
                        <span className="font-mono text-[11px] text-nordic-gold font-bold">
                          {lvl.requiredPoints.toLocaleString()} pts
                        </span>
                      </div>
                      <span className="text-[10px] text-nordic-muted block truncate mb-1.5">
                        {lvl.perks[0] || 'Desbloqueo de talentos'}
                      </span>
                      <div className="pt-1.5 border-t border-nordic-border/50 text-[10px] font-mono text-nordic-gold flex items-center justify-between">
                        <span>⛏️ {picosNeeded} Picos</span>
                        <span className="text-nordic-muted">o 🗡️ {espadasNeeded} Espadas</span>
                      </div>
                    </button>
                  );
                })}
            </div>

            {/* Input Manual de Puntos & Slider de Durabilidad */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2 border-t border-nordic-border">
              <div>
                <label className="block text-xs font-semibold text-nordic-muted uppercase tracking-wider mb-2">
                  Puntos de Maestría Requeridos (Personalizado)
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="number"
                    min="1"
                    step="50"
                    value={altarTargetPoints}
                    onChange={(e) => setAltarTargetPoints(Number(e.target.value))}
                    aria-label="Puntos de maestría requeridos"
                    className="flex-1 bg-nordic-card border border-nordic-border rounded-xl px-4 py-2.5 text-base font-mono font-bold text-nordic-gold focus:outline-none focus:border-nordic-gold"
                  />
                  <button
                    onClick={() => setAltarTargetPoints(1000)}
                    className="px-3 py-2.5 bg-nordic-card border border-nordic-border rounded-xl text-xs text-nordic-muted hover:text-nordic-gold"
                  >
                    1k
                  </button>
                  <button
                    onClick={() => setAltarTargetPoints(4200)}
                    className="px-3 py-2.5 bg-nordic-card border border-nordic-border rounded-xl text-xs text-nordic-muted hover:text-nordic-gold"
                  >
                    4.2k
                  </button>
                </div>
              </div>

              <div>
                <div className="flex items-center justify-between mb-2">
                  <label className="text-xs font-semibold text-nordic-muted uppercase tracking-wider">
                    Durabilidad del Lote a Donar
                  </label>
                  <span className={`text-xs font-mono font-bold ${inverseDurability === 100 ? 'text-emerald-400' : 'text-amber-400'}`}>
                    {inverseDurability}%
                  </span>
                </div>
                <input
                  type="range"
                  min="10"
                  max="100"
                  step="5"
                  value={inverseDurability}
                  onChange={(e) => setInverseDurability(Number(e.target.value))}
                  aria-label="Durabilidad del lote a donar"
                  className="w-full accent-nordic-gold h-2 bg-nordic-card rounded-lg cursor-pointer"
                />
                <span className="text-[11px] text-nordic-muted block mt-1">
                  💡 <strong>Tip pro:</strong> En Frostborn un ítem al 50% de durabilidad da el 50% de puntos.
                </span>
              </div>
            </div>
          </div>

          {/* Banner de Aviso de Eficiencia */}
          <div className="bg-amber-950/20 border border-amber-800/40 rounded-xl p-3.5 flex items-start gap-3 text-xs text-amber-200">
            <Info className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-amber-300 mb-0.5">
                Fórmula de Donación Óptima de la Comunidad
              </p>
              <p className="text-amber-200/80">
                Los <strong>Picos Fuertes</strong> y las <strong>Espadas/Escudos Verdes</strong> ofrecen el ratio más alto de puntos por lingote de cobre invertido. Evita craftear gorros de tela o lanzas de madera rústicas.
              </p>
            </div>
          </div>

          {/* Opciones Recomendadas Ordenadas por Eficiencia */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs uppercase tracking-wider text-nordic-muted font-semibold">
                Opciones Recomendadas ({recommendedPlans.length})
              </span>
              <span className="text-xs text-nordic-gold font-medium">
                Meta: {altarTargetPoints.toLocaleString()} puntos
              </span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {recommendedPlans.map((plan) => {
                const isTop = plan.efficiencyRating === 'top';
                const isHigh = plan.efficiencyRating === 'high';
                const isLow = plan.efficiencyRating === 'low';

                return (
                  <div
                    key={plan.item.id}
                    className={`rounded-2xl border p-4 transition-all relative overflow-hidden flex flex-col justify-between ${
                      isTop
                        ? 'bg-nordic-card/90 border-amber-500/60 shadow-lg shadow-amber-500/5'
                        : isHigh
                        ? 'bg-nordic-surface border-nordic-border hover:border-nordic-gold/40'
                        : 'bg-nordic-surface/40 border-nordic-border/50 opacity-75'
                    }`}
                  >
                    <div>
                      {/* Header del ítem */}
                      <div className="flex items-start justify-between gap-3 mb-3">
                        <div className="flex items-center gap-3">
                          <span className="text-3xl p-2 rounded-xl bg-nordic-card border border-nordic-border">
                            {plan.item.icon || '⚔️'}
                          </span>
                          <div>
                            <div className="flex items-center gap-2">
                              <h4 className="font-bold text-sm text-nordic-text">
                                {plan.item.name}
                              </h4>
                              {isTop && (
                                <span className="px-2 py-0.5 rounded-full bg-amber-500/20 text-amber-300 border border-amber-500/50 text-[10px] font-semibold flex items-center gap-1">
                                  <Crown className="w-3 h-3" /> TOP
                                </span>
                              )}
                              {isHigh && (
                                <span className="px-2 py-0.5 rounded-full bg-emerald-500/15 text-emerald-300 border border-emerald-500/40 text-[10px] font-semibold flex items-center gap-1">
                                  <Zap className="w-3 h-3" /> Alta
                                </span>
                              )}
                              {isLow && (
                                <span className="px-2 py-0.5 rounded-full bg-red-950/40 text-red-300 border border-red-800/40 text-[10px] font-semibold flex items-center gap-1">
                                  <AlertTriangle className="w-3 h-3" /> Bajo ratio
                                </span>
                              )}
                            </div>
                            <span className="text-[11px] text-nordic-muted">
                              {plan.pointsPerItem} pts por unidad (al {inverseDurability}% durabilidad)
                            </span>
                          </div>
                        </div>

                        <div className="text-right">
                          <span className="font-runic font-bold text-lg text-nordic-gold block">
                            {plan.itemsNeeded.toLocaleString()} un.
                          </span>
                          <span className="text-[10px] text-nordic-muted font-mono">
                            = {plan.totalPointsGenerated.toLocaleString()} pts
                          </span>
                        </div>
                      </div>

                      {/* Nota contextual */}
                      {plan.item.notes && (
                        <p className="text-xs text-nordic-muted mb-3 italic">
                          {plan.item.notes}
                        </p>
                      )}
                    </div>

                    {/* Desglose de Crafteo Total */}
                    {plan.totalCraftMaterials && (
                      <div className="mt-2 pt-3 border-t border-nordic-border/70 bg-nordic-card/40 -mx-4 -mb-4 p-3 rounded-b-2xl">
                        <span className="text-[10px] uppercase font-semibold text-nordic-muted block mb-1.5">
                          Coste total de materiales para fabricar {plan.itemsNeeded} unidades:
                        </span>
                        <div className="flex flex-wrap gap-2">
                          {Object.entries(plan.totalCraftMaterials).map(([matId, qty]) => {
                            const meta = KNOWN_MATERIALS[matId];
                            const name = meta ? meta.name : matId;
                            const icon = meta ? meta.icon : '📦';
                            return (
                              <span
                                key={matId}
                                className="px-2 py-1 rounded-md bg-nordic-surface border border-nordic-border text-xs font-mono text-nordic-text flex items-center gap-1.5"
                              >
                                <span>{icon}</span>
                                <span>{name}:</span>
                                <strong className="text-nordic-gold">{qty.toLocaleString()}</strong>
                              </span>
                            );
                          })}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}

      {/* ========================================================= */}
      {/* MODO 2: CALCULADOR DIRECTO DE LOTE (MI INVENTARIO)         */}
      {/* ========================================================= */}
      {altarMode === 'direct' && (
        <div className="space-y-6">
          {/* Resumen Superior */}
          <div className="bg-nordic-surface rounded-2xl border border-nordic-border p-5 shadow-lg flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <span className="text-xs text-nordic-muted uppercase font-semibold tracking-wider">
                Total de Puntos de Maestría Obtenidos
              </span>
              <div className="flex items-baseline gap-2 mt-1">
                <span className="font-runic font-bold text-3xl text-nordic-gold">
                  {totalBatchPoints.toLocaleString()}
                </span>
                <span className="text-sm text-nordic-muted font-medium">puntos</span>
              </div>
              <p className="text-xs text-nordic-muted mt-1">
                {altarBatch.length === 0
                  ? 'Agrega armas o armaduras para calcular los puntos exactos'
                  : `Lote actual con ${altarBatch.reduce((sum, i) => sum + i.quantity, 0)} piezas listas para ofrendar`}
              </p>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => addBatchItem('strong_pickaxe', 100, 5)}
                className="px-3 py-2 rounded-xl bg-nordic-card hover:bg-nordic-border border border-nordic-border text-xs text-nordic-text flex items-center gap-1.5 transition-colors"
              >
                <Plus className="w-3.5 h-3.5 text-nordic-gold" />
                <span>+5 Picos Fuertes</span>
              </button>
              {altarBatch.length > 0 && (
                <button
                  onClick={clearBatch}
                  className="px-3 py-2 rounded-xl bg-nordic-card hover:bg-nordic-border border border-nordic-border text-xs text-nordic-blood flex items-center gap-1.5 transition-colors"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                  <span>Limpiar</span>
                </button>
              )}
            </div>
          </div>

          {/* Formulario para agregar item al lote */}
          <div className="bg-nordic-surface rounded-2xl border border-nordic-border p-4">
            <h3 className="text-xs font-semibold uppercase text-nordic-muted mb-3">
              Agregar Ítem al Lote de Sacrificio
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div className="sm:col-span-2">
                <select
                  id="addItemSelect"
                  aria-label="Seleccionar ítem para agregar al lote"
                  defaultValue="green_sword"
                  className="w-full bg-nordic-card border border-nordic-border rounded-xl px-3 py-2.5 text-sm text-nordic-text focus:outline-none focus:border-nordic-gold"
                >
                  {itemsData.map(i => (
                    <option key={i.id} value={i.id}>
                      {i.icon} {i.name} ({i.masteryPoints} pts base) — {i.rarity.toUpperCase()}
                    </option>
                  ))}
                </select>
              </div>

              <button
                onClick={() => {
                  const select = document.getElementById('addItemSelect') as HTMLSelectElement;
                  if (select) {
                    addBatchItem(select.value, 100, 1);
                  }
                }}
                className="px-4 py-2.5 bg-nordic-gold hover:bg-nordic-gold-light text-black font-bold rounded-xl text-sm flex items-center justify-center gap-1.5 transition-all"
              >
                <Plus className="w-4 h-4" />
                <span>Agregar al Lote</span>
              </button>
            </div>
          </div>

          {/* Lista del lote actual */}
          <div className="space-y-3">
            {altarBatch.map((entry) => {
              const item = itemsData.find(i => i.id === entry.itemId);
              if (!item) return null;

              const unitPoints = calculateDonationPoints(item.masteryPoints, entry.durability, 1);
              const entryTotalPoints = unitPoints * entry.quantity;

              return (
                <div
                  key={entry.id}
                  className="bg-nordic-surface rounded-xl border border-nordic-border p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4"
                >
                  <div className="flex items-center gap-3">
                    <span className="text-2xl p-2 rounded-lg bg-nordic-card border border-nordic-border">
                      {item.icon || '⚔️'}
                    </span>
                    <div>
                      <h4 className="font-semibold text-sm text-nordic-text">
                        {item.name}
                      </h4>
                      <span className="text-xs text-nordic-muted font-mono">
                        {entryTotalPoints} pts ({unitPoints} pts × {entry.quantity} un.)
                      </span>
                    </div>
                  </div>

                  <div className="flex flex-col sm:flex-row sm:items-center gap-4">
                    {/* Control de Cantidad */}
                    <div className="flex items-center gap-2">
                      <span className="text-xs text-nordic-muted">Cant:</span>
                      <input
                        type="number"
                        min="1"
                        max="999"
                        value={entry.quantity}
                        onChange={(e) => updateBatchItem(entry.id, { quantity: Math.max(1, Number(e.target.value)) })}
                        aria-label={`Cantidad para ${item.name}`}
                        className="w-16 bg-nordic-card border border-nordic-border rounded-lg px-2 py-1 text-sm font-mono text-nordic-text text-center"
                      />
                    </div>

                    {/* Control de Durabilidad Slider */}
                    <div className="flex items-center gap-2 w-48">
                      <span className="text-xs text-nordic-muted">Dur:</span>
                      <input
                        type="range"
                        min="5"
                        max="100"
                        step="5"
                        value={entry.durability}
                        onChange={(e) => updateBatchItem(entry.id, { durability: Number(e.target.value) })}
                        aria-label={`Durabilidad para ${item.name}`}
                        className="w-full accent-nordic-gold h-1.5 bg-nordic-card rounded cursor-pointer"
                      />
                      <span className="text-xs font-mono font-bold text-nordic-gold w-10 text-right">
                        {entry.durability}%
                      </span>
                    </div>

                    <button
                      onClick={() => removeBatchItem(entry.id)}
                      className="p-1.5 text-nordic-muted hover:text-nordic-blood rounded-lg hover:bg-nordic-card transition-colors self-end sm:self-center"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* ========================================================= */}
      {/* MODO 3: CATÁLOGO DE ÍTEMS DONABLES                        */}
      {/* ========================================================= */}
      {altarMode === 'catalog' && (
        <div className="space-y-4">
          {/* Filtros y Búsqueda */}
          <div className="bg-nordic-surface rounded-2xl border border-nordic-border p-4 grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div className="relative sm:col-span-1">
              <Search className="w-4 h-4 absolute left-3 top-3 text-nordic-muted" />
              <input
                type="text"
                placeholder="Buscar arma o armadura..."
                value={catalogSearch}
                onChange={(e) => setCatalogSearch(e.target.value)}
                className="w-full bg-nordic-card border border-nordic-border rounded-xl pl-9 pr-3 py-2 text-sm text-nordic-text focus:outline-none focus:border-nordic-gold"
              />
            </div>

            <select
              value={catalogRarityFilter}
              onChange={(e) => setCatalogRarityFilter(e.target.value)}
              aria-label="Filtrar por rareza"
              className="bg-nordic-card border border-nordic-border rounded-xl px-3 py-2 text-sm text-nordic-text focus:outline-none focus:border-nordic-gold"
            >
              <option value="all">Todas las Rarezas</option>
              <option value="common">Común (Gris)</option>
              <option value="uncommon">Poco Común (Verde)</option>
              <option value="rare">Raro (Azul)</option>
              <option value="epic">Épico (Morado)</option>
              <option value="legendary">Legendario (Dorado)</option>
            </select>

            <select
              value={catalogTypeFilter}
              onChange={(e) => setCatalogTypeFilter(e.target.value)}
              aria-label="Filtrar por tipo"
              className="bg-nordic-card border border-nordic-border rounded-xl px-3 py-2 text-sm text-nordic-text focus:outline-none focus:border-nordic-gold"
            >
              <option value="all">Todos los Tipos</option>
              <option value="weapon">Armas</option>
              <option value="armor">Armaduras</option>
              <option value="tool">Herramientas</option>
              <option value="magic">Mágicos</option>
            </select>
          </div>

          {/* Tabla de ítems */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {filteredCatalogItems.map((item) => {
              const rarityStyle = RARITY_COLORS[item.rarity as Rarity] || RARITY_COLORS.common;

              return (
                <div
                  key={item.id}
                  className="bg-nordic-surface rounded-xl border border-nordic-border p-4 flex flex-col justify-between"
                >
                  <div className="flex items-start justify-between gap-3 mb-2">
                    <div className="flex items-center gap-3">
                      <span className="text-3xl p-2 bg-nordic-card rounded-xl border border-nordic-border">
                        {item.icon || '⚔️'}
                      </span>
                      <div>
                        <h4 className="font-bold text-sm text-nordic-text">{item.name}</h4>
                        <span className={`text-[10px] px-2 py-0.5 rounded font-semibold uppercase ${rarityStyle.badge}`}>
                          {item.rarity}
                        </span>
                      </div>
                    </div>

                    <div className="text-right">
                      <span className="font-runic font-bold text-base text-nordic-gold block">
                        {item.masteryPoints} pts
                      </span>
                      <span className="text-[10px] text-nordic-muted">
                        Dur: {item.maxDurability}
                      </span>
                    </div>
                  </div>

                  {item.notes && (
                    <p className="text-xs text-nordic-muted my-2">
                      {item.notes}
                    </p>
                  )}

                  {item.craftRecipe && (
                    <div className="pt-2 border-t border-nordic-border/60 flex flex-wrap gap-1.5 mt-auto">
                      {Object.entries(item.craftRecipe).map(([mId, qty]) => {
                        const meta = KNOWN_MATERIALS[mId];
                        return (
                          <span
                            key={mId}
                            className="text-[11px] font-mono text-nordic-muted bg-nordic-card px-2 py-0.5 rounded border border-nordic-border"
                          >
                            {meta ? meta.name : mId}: {qty}
                          </span>
                        );
                      })}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
};
